apiVersion: v2
name: hatchet-api
description: A Helm chart for deploying Hatchet API components on Kubernetes.
type: application
icon: https://hatchet.run/brand/logomark-white-bg.svg
version: 0.13.2
home: https://hatchet.run
sources:
  - https://github.com/hatchet-dev/hatchet-charts
  - https://github.com/hatchet-dev/hatchet
keywords:
  - hatchet
  - workflow
  - workflows
  - task-queue
  - orchestration
  - durable-execution
  - background-jobs
maintainers:
  - name: Hatchet Engineering
    email: alexander@hatchet.run
annotations:
  artifacthub.io/signKey: |
    fingerprint: E087E4C6368DB465CB6A75BE779CE2A7829DEA1A
    url: https://raw.githubusercontent.com/hatchet-dev/hatchet-charts/main/KEYS
