apiVersion: v2
name: hatchet-ha
description: A Helm chart for deploying Hatchet in a high-availability configuration
type: application
version: 0.9.2
maintainers:
  - name: Hatchet Engineering
    email: alexander@hatchet.run
dependencies:
  - name: "hatchet-api"
    condition: api.enabled
    repository: "file://../hatchet-api"
    version: "^0.9.2"
    alias: api
  - name: "hatchet-api"
    condition: grpc.enabled
    repository: "file://../hatchet-api"
    version: "^0.9.2"
    alias: grpc
  - name: "hatchet-api"
    condition: controllers.enabled
    repository: "file://../hatchet-api"
    version: "^0.9.2"
    alias: controllers
  - name: "hatchet-api"
    condition: scheduler.enabled
    repository: "file://../hatchet-api"
    version: "^0.9.2"
    alias: scheduler
  - name: "hatchet-frontend"
    condition: frontend.enabled
    repository: "file://../hatchet-frontend"
    version: "^0.9.2"
    alias: frontend
  - name: "postgresql"
    condition: postgres.enabled
    repository: "https://charts.bitnami.com/bitnami"
    version: "^14.2.1"
    alias: postgres
  - name: "rabbitmq"
    condition: rabbitmq.enabled
    repository: "https://charts.bitnami.com/bitnami"
    version: "^12.13.1"
    alias: rabbitmq
