rabbitmq:
  enabled: false
postgres:
  instances: 1
  storage:
    size: 1Gi
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
sharedConfig:
  env:
    SERVER_MSGQUEUE_KIND: postgres
    SERVER_SECURITY_CHECK_ENABLED: "false"
api:
  replicaCount: 1
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
grpc:
  replicaCount: 1
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
controllers:
  replicaCount: 1
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
scheduler:
  replicaCount: 1
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
frontend:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
