rabbitmq:
  enabled: false
postgres:
  primary:
    extendedConfiguration: "timezone='UTC'"
    resourcesPreset: "small"
sharedConfig:
  env:
    SERVER_MSGQUEUE_KIND: postgres
api:
  replicaCount: 1
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
engine:
  replicaCount: 1
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
frontend:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
