{{- if .Values.podDisruptionBudget }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ template "hatchet.fullname" . }}
spec:
  {{ toYaml .Values.podDisruptionBudget }}
  selector:
    matchLabels:
  {{- include "hatchet.selectorLabels" . | nindent 6 }}
{{- end }}
